import Head from "next/head";
import NavButton from "../components/NavButton";
import Container from "../components/Container";
import Button from "../components/Button";
import styles from "../../styles/Home.module.css";
import styled from "styled-components";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <NavButton />
        <Container>
          <div className={styles.content}>
            <h1 className={styles.header}>AnatoMate</h1>
            <h2 className={styled.description}>
              &emsp;A web application for artist who want an improvement. We can
              help suggest what you should focus to improve your human anatomy
              drawing.
            </h2>
            <Button style={{ fontSize: "1.5em" }}>Try now</Button>
          </div>
        </Container>
      </main>
    </div>
  );
}
